INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Allt går sönder ','Chinua Achebe','2212.47','August 25, 1914')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Drottningens juvelsmycke','Carl Jonas Love Almqvist','412.6','May 18, 1927')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Andarnas hus +','Isabel Allende','1320.24','December 31, 1927')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Ditte människobarn','Martin Andersen Nexö','1289.18','April 22, 1934')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Hitom himlen','Stina Aronson','1186.11','July 17, 1940')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Stolthet och fördom ','Jane Austen','1244.99','February 26, 1941')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Pappa Goriot ','Honoré de Balzac','1804.21','September 29, 1941')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Ondskans blommor','Charles Baudelaire','827.25','February 9, 1943')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('I väntan på Godot+','Samuel Beckett','1013.1','March 16, 1948')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Onkel Toms stuga',' Harriet Beecher Stowe','1860.9','December 31, 1948')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Fru Marianne ',' Victoria Benedictsson','1673.48','March 14, 1951')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Röde Orm',' Frans G. Bengtsson','213.49','May 16, 1956')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Markurells i Wadköping (sett en teaterföreställn',' Hjalmar Bergman','2174.14','November 9, 1964')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Decamerone',' Giovanni Boccaccio','938.58','May 30, 1969')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Kallocain ',' Karin Boye','1969.16','June 28, 1970')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Mor Courage och hennes barn',' Bertholt Brecht','1226.96','September 10, 1972')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Hertha',' Fredrika Bremer','1182.1','November 25, 1974')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Agnes Grey',' Anne Brontë','1611.15','October 25, 1976')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Jane Eyre ',' Charlotte Brontë','2483.79','November 11, 1985')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Svindlande höjder',' Emily Brontë','1478.33','February 12, 2005')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Mästaren och Margarita',' Mikhail Bulgakov','1437.93','November 23, 2013')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Om en vinternatt en resande *',' Italo Calvino','2149.59','October 8, 2014')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Främlingen +',' Albert Camus','1879.74','March 8, 2015')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Drömmar om röda gemak',' Cao Xueqin','988.19','March 17, 2015')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Don Quijote',' Cervantes','2220.61','May 27, 2016')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Mörkrets hjärta',' Joseph Conrad','1976.74','April 12, 1922')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den gudomliga komedin',' Dante Alighieri','2469.78','June 13, 1927')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Robinson Crusoe ',' Daniel Defoe','2238.14','December 10, 1927')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Oliver Twist ',' Charles Dickens','2318.39','October 6, 1929')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Brott och straff +',' Fjodor Dostojevskij','2298.18','July 18, 1931')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('De tre musketörerna ',' Alexandre Dumas d ä','1479.45','July 6, 1935')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Älskaren +',' Marguerite Duras','1611.73','July 14, 1939')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Det öde landet+',' T S Eliot','533.14','August 7, 1940')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Medea+',' Euripides','2390.12','July 11, 1946')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Absalom, Absalom',' William Faulkner','1411.26','September 20, 1955')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den store Gatsby+',' F Scott Fitzgerald','857.89','July 26, 1956')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Madame Bovary',' Gustave Flaubert','1582.75','September 15, 1957')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Rosen på Tistelön',' Emilie Flygare-Carlén','1796.90','November 28, 1962')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Stockholms-serien +',' Per Anders Fogelström','309.82','June 28, 1964')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Hundra år av ensamhet +',' Gabriel García Márquez','2100.28','November 30, 1967')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den omoraliske',' André Gide','1453.24','June 7, 1968')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den unge Werthers lidanden ',' Johann Wolfgang von Goethe','1185.14','October 6, 1989')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Min barndom',' Maksim Gorkij','459.68','January 20, 1996')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Brighton Rock',' Graham Greene','2250.20','June 25, 1999')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Markens gröda',' Knut Hamsun','1308.88','April 21, 2002')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den tappre soldaten Svejk',' Jaroslav Hasek','1813.10','September 13, 2010')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Moment 22',' Joseph Heller','324.92','February 9, 2011')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den gamle och havet ',' Ernest Hemingway','2285.30','February 13, 2012')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Stäppvargen?',' Hermann Hesse','2161.68','December 3, 2013')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Odysséen',' Homeros','2441.33','March 28, 2014')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Et dukkehjem',' Henrik Ibsen','623.92','October 17, 1921')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Strändernas svall',' Eyvind Johnson','975.62','May 31, 1922')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Ulysses',' James Joyce','1473.45','May 30, 1926')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Processen ',' Franz Kafka','1061.5','December 29, 1927')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Låt tistlarna brinna!',' Yasar Kemal','856.13','November 4, 1930')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Bertha Funke*',' Kleve, Stella (Malling, Math','1678.59','October 25, 1935')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Barabbas +',' Pär Lagerkvist','1516.20','April 10, 1941')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Kejsarn av Portugallien ',' Selma Lagerlöf','1652.24','September 30, 1941')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Lifsens rot',' Lidman, Sara','1395.19','February 7, 1944')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Okänd soldat (har läst utdrag, räknas det?)',' Väinö Linna','1128.33','March 29, 1959')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Kungsgatan',' Ivar Lo-Johansson','603.87','December 23, 1963')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Huset Buddenbrook',' Thomas Mann','1389.89','November 30, 1967')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Nässlorna blomma',' Harry Martinson','515.86','July 19, 1968')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Kvinnor och äppelträd',' Moa Martinson','276.66','October 28, 1976')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Utvandrar-serien',' Vilhelm Moberg','1353.11','March 27, 1977')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Tartuffe',' Molière','907.64','September 13, 1981')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Historien*',' Elsa Morante','1740.71','May 9, 1993')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Älskade ',' Morrison, Toni','863.83','January 23, 1995')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Lolita',' Vladimir Nabokov','2289.4','February 3, 1995')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('1984 +',' George Orwell','439.94','April 16, 1998')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Doktor Zjivago',' Boris Pasternak','719.20','May 30, 1998')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Kärleksdikter',' Francesco Petrarca','1543.61','October 11, 2001')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('På spaning efter den tid som flytt ',' Marcel Proust','2170.35','April 3, 2004')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('På Västfronten intet nytt ',' Erich Maria Remarque','1937.23','November 13, 2016')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Räddaren i nöden',' J. D. Salinger','2094.86','August 13, 2018')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Alberte-serien x läst första delen i serien.',' Cora Sandel','2282.76','June 27, 1914')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Dikter och fragment',' Sapfo','234.27','November 6, 1917')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Macbeth+',' William Shakespeare','344.41','August 2, 1921')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Frankenstein ',' Mary Shelley','1103.81','October 31, 1921')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Konung Oidipus',' Sofokles','2092.69','October 13, 1922')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('En dag i Ivan Denisovitjs liv ',' Solzjenitsyn','2078.67','July 20, 1930')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Vredens druvor',' John Steinbeck','1948.83','April 3, 1936')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Rött och svart*',' Stendhal','2439.47','January 12, 1942')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Dracula',' Bram Stoker','1318.97','January 12, 1943')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Dr Jekyll och Mr Hyde',' Robert Louis Stevenson','1400.6','May 8, 1944')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Röda rummet',' August Strindberg','671.70','January 24, 1948')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Egil Skallagrimssons saga',' Snorre Sturlasson (?)','213.75','September 16, 1951')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Gullivers resor',' Jonathan Swift','1187.12','April 29, 1955')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Den allvarsamma leken +',' Hjalmar Söderberg','1094.62','January 3, 1958')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Damen med hunden ',' Anton Tjechov','1898.58','October 23, 1958')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Anna Karenina +',' Lev Tolstoj','796.47','February 27, 1965')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Huckleberry Finn',' Mark Twain','1496.50','July 12, 1976')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Kristin Lavransdotter',' Sigrid Undset','869.87','August 7, 1978')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Jorden runt på 80 dagar +',' Jules Verne','554.14','June 30, 1985')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Candide ',' Voltaire','2295.42','April 24, 1986')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Dorian Grays porträtt ',' Oscar Wilde','815.75','June 8, 1991')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Mot fyren',' Woolf, Virginia','591.16','April 14, 2002')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Pennskaftet',' Wägner, Elin','980.2','December 24, 2005')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Tornet',' William Butler Yeats','1066.40','December 20, 2007')
INSERT INTO BOOK (TITLE, AUTHOR, PRICE, DATE) VALUES ('Thérèse Raquin','Émile Zola','1483.89','June 23, 2016')
