CREATE TABLE BOOK(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  AUTHOR VARCHAR(64) NOT NULL,
  PRICE DOUBLE NOT NULL,
  DATE VARCHAR(64) NOT NULL,
  THUMBNAIL VARCHAR(255) NOT NULL

);

CREATE TABLE USERS(
  ID LONG AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(64),
  ROLES VARCHAR(64),
  PASSWORD VARCHAR(64)

);

CREATE TABLE CART(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BOOKID BIGINT,
  QTY BIGINT,
);


CREATE TABLE ROLES(
  ID LONG AUTO_INCREMENT PRIMARY KEY,
  ROLES VARCHAR(64),
);

